name: Audit

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  Audit:
    runs-on: ubuntu-latest
    uses: actions/github-script@v6.0.0
    steps:
      - name: Get Audit Logs
          with:
            github-token: ${{secrets.AUDIT_TOKEN}}
            script: |
              let auditLog = await github.request("GET /orgs/northerntrust-internal/audit-log",
                                   params={
                                            phrase:'action:repo.rename action:repo.add_member'
                                            })
              console.log(auditLog.data)
    

